# Generated by Django 2.2.5 on 2021-04-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Description', models.TextField()),
                ('Coordinator1', models.CharField(max_length=100)),
                ('Corrdinator1_email', models.CharField(max_length=100)),
                ('Coordinator2', models.CharField(max_length=100)),
                ('Corrdinator2_email', models.CharField(max_length=100)),
                ('Coordinator3', models.CharField(max_length=100)),
                ('Corrdinator3_email', models.CharField(max_length=100)),
                ('FB_link', models.URLField()),
                ('IG_link', models.URLField()),
                ('Website_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Club_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt', models.ImageField(blank=True, upload_to='clubs/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
    ]
