# Generated by Django 3.0.5 on 2021-03-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Club_Events',
            new_name='BIOBYTES',
        ),
    ]
