# Generated by Django 3.0.5 on 2021-03-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0002_auto_20210310_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASTRONUTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='astronuts/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='astronuts/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AUDIOBYTES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='audiobytes/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='audiobytes/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BYLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='byld/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='byld/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ELECTROHOLICS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='electroholics/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='electroholics/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FOOBAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='foobar/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='foobar/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KUBIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='kubic/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='kubic/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MACHAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='machan/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='machan/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MADTOES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='madtoes/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='madtoes/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PHILOSOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='philosoc/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='philosoc/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ROBOTICS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='robotics/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='robotics/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TASVEER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='tasveer/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='tasveer/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='THE65SQUARE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='the65square/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='the65square/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TRIVIALIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='trivialis/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='trivialis/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='biobytes',
            name='Payment_receipt',
        ),
        migrations.AddField(
            model_name='biobytes',
            name='Payment_receipt_reimburse',
            field=models.ImageField(null=True, upload_to='biobytes/office/payment_receipt'),
        ),
        migrations.AddField(
            model_name='biobytes',
            name='Payment_receipt_student',
            field=models.ImageField(null=True, upload_to='biobytes/student/payment_receipt'),
        ),
    ]
