# Generated by Django 3.0.5 on 2021-03-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0003_auto_20210310_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biobytes',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
