# Generated by Django 3.0.5 on 2021-03-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0004_auto_20210311_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biobytes',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
