# Generated by Django 3.0.5 on 2021-03-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0005_auto_20210311_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLUB_GENERAl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Coordinator1', models.CharField(max_length=100)),
                ('Corrdinator1_email', models.CharField(max_length=100)),
                ('Coordinator2', models.CharField(max_length=100)),
                ('Corrdinator2_email', models.CharField(max_length=100)),
                ('Coordinato3', models.CharField(max_length=100)),
                ('Corrdinator3_email', models.CharField(max_length=100)),
                ('FB_link', models.URLField()),
                ('IG_link', models.URLField()),
                ('Website_link', models.URLField()),
            ],
        ),
    ]
