# Generated by Django 3.0.5 on 2021-03-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0006_club_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLUB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Location', models.URLField(max_length=500)),
                ('Description', models.TextField()),
                ('Payment_receipt_student', models.ImageField(null=True, upload_to='club/student/payment_receipt')),
                ('Payment_receipt_reimburse', models.ImageField(null=True, upload_to='club/office/payment_receipt')),
                ('Approved', models.BooleanField(default=False)),
                ('Attendance', models.IntegerField(default=0)),
                ('Club_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ASTRONUTS',
        ),
        migrations.DeleteModel(
            name='AUDIOBYTES',
        ),
        migrations.DeleteModel(
            name='BIOBYTES',
        ),
        migrations.DeleteModel(
            name='BYLD',
        ),
        migrations.DeleteModel(
            name='ELECTROHOLICS',
        ),
        migrations.DeleteModel(
            name='FOOBAR',
        ),
        migrations.DeleteModel(
            name='KUBIC',
        ),
        migrations.DeleteModel(
            name='MACHAN',
        ),
        migrations.DeleteModel(
            name='MADTOES',
        ),
        migrations.DeleteModel(
            name='PHILOSOC',
        ),
        migrations.DeleteModel(
            name='ROBOTICS',
        ),
        migrations.DeleteModel(
            name='TASVEER',
        ),
        migrations.DeleteModel(
            name='THE65SQUARE',
        ),
        migrations.DeleteModel(
            name='TRIVIALIS',
        ),
    ]
