# Generated by Django 3.0.5 on 2021-03-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0007_auto_20210312_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='Location',
            field=models.CharField(max_length=200),
        ),
    ]
