# Generated by Django 3.0.5 on 2021-03-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0008_auto_20210313_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='Approved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='Attendance',
            new_name='attendance',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='Club_name',
            new_name='club_name',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='Time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='club_general',
            old_name='Coordinato3',
            new_name='coordinato3',
        ),
        migrations.RenameField(
            model_name='club_general',
            old_name='Coordinator1',
            new_name='coordinator1',
        ),
        migrations.RenameField(
            model_name='club_general',
            old_name='Coordinator2',
            new_name='coordinator2',
        ),
        migrations.RenameField(
            model_name='club_general',
            old_name='Corrdinator1_email',
            new_name='corrdinator1_email',
        ),
        migrations.RenameField(
            model_name='club_general',
            old_name='Corrdinator2_email',
            new_name='corrdinator2_email',
        ),
        migrations.RenameField(
            model_name='club_general',
            old_name='Corrdinator3_email',
            new_name='corrdinator3_email',
        ),
        migrations.RenameField(
            model_name='club_general',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='club_general',
            old_name='FB_link',
            new_name='fB_link',
        ),
        migrations.RenameField(
            model_name='club_general',
            old_name='IG_link',
            new_name='iG_link',
        ),
        migrations.RenameField(
            model_name='club_general',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='club_general',
            old_name='Website_link',
            new_name='website_link',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='club',
            name='Payment_receipt_reimburse',
        ),
        migrations.RemoveField(
            model_name='club',
            name='Payment_receipt_student',
        ),
        migrations.AddField(
            model_name='club',
            name='payment_receipt_reimburse',
            field=models.ImageField(blank=True, upload_to='club/office/payment_receipt'),
        ),
        migrations.AddField(
            model_name='club',
            name='payment_receipt_student',
            field=models.ImageField(blank=True, upload_to='club/student/payment_receipt'),
        ),
    ]
