# Generated by Django 3.0.5 on 2021-03-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0009_auto_20210313_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='time',
            new_name='date_time',
        ),
    ]
