# Generated by Django 3.0.5 on 2021-03-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0012_auto_20210317_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_general',
            old_name='coordinato3',
            new_name='coordinator3',
        ),
    ]
