# Generated by Django 3.0.5 on 2021-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0013_auto_20210317_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_general',
            name='coordinator2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club_general',
            name='coordinator2_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club_general',
            name='coordinator3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club_general',
            name='coordinator3_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club_general',
            name='fb_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='club_general',
            name='ig_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='club_general',
            name='website_link',
            field=models.URLField(blank=True),
        ),
    ]
