# Generated by Django 3.0.5 on 2021-03-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0011_user_details'),
        ('stakeholder', '0014_auto_20210317_2332'),
    ]

    operations = [
    ]
