# Generated by Django 3.0.5 on 2021-03-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0015_merge_20210328_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='payment_receipt_reimburse',
            field=models.FileField(blank=True, upload_to='club/office/payment_receipt'),
        ),
        migrations.AlterField(
            model_name='club',
            name='payment_receipt_student',
            field=models.FileField(blank=True, upload_to='club/student/payment_receipt'),
        ),
    ]
