# Generated by Django 3.0.5 on 2021-03-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0018_auto_20210330_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CredentialsModel',
        ),
    ]
