# Generated by Django 3.0.5 on 2021-03-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0020_auto_20210331_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecredentials',
            name='scopes',
        ),
    ]
