"""
Django settings for Club_Management project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "iw5_v3eol$+ioc2hd+dbxb9gt-r+gskqwg_+@f4!u(ub40v%il"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
SITE_ID=2

AUTHENTICATION_BACKENDS = (

 'django.contrib.auth.backends.ModelBackend',
 'allauth.account.auth_backends.AuthenticationBackend'
)
# Application definition

INSTALLED_APPS = [
   'stakeholder',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "rest_framework",
     'corsheaders',
    "frontend",
     'allauth',   # <--
 'allauth.account',   # <--
 'allauth.socialaccount',   # <--
 'allauth.socialaccount.providers.google', 

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
]

ROOT_URLCONF = "Club_Management.urls"
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = [
     'http://localhost:3000','http://localhost:8081'
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "../frontend")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Club_Management.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        "CLIENT": {
          "name": 'CLUB_MANAGEMENT_PORTAL_DB',
           "host": 'mongodb+srv://Admin:UorNOwLkoopfBZWS@cluster0.zm97q.mongodb.net/CLUB_MANAGEMENT_PORTAL_DB?retryWrites=true&w=majority',
           "username": 'Admin',
           "password": 'UorNOwLkoopfBZWS',
           "authMechanism": "SCRAM-SHA-1",
        }, 
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "../frontend/build/static"),
]
GOOGLE_OAUTH2_CLIENT_SECRETS_JSON = 'client_secrets.json'
GOOGLE_OAUTH2_CLIENT_ID='426037707978-88edj8k1aka47he62l7l3l6rkf42tbmh.apps.googleusercontent.com'
GOOGLE_OAUTH2_SECRET_KEY='3nwr-fEV3sigJ187nDOP1NoZ'
GOOGLE_OAUTH2_TOKEN_URI='https://oauth2.googleapis.com/token'
GOOGLE_OAUTH2_SCOPES=['https://www.googleapis.com/auth/calendar.events','https://www.googleapis.com/auth/userinfo.profile','https://www.googleapis.com/auth/userinfo.email','openid']
GOOGLE_OAUTH2_API_SERVICE_NAME='calendar'
GOOGLE_OAUTH2_API_VERSION='v3'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"

LOGIN_REDIRECT_URL ="/"

#AUTH_USER_MODEL='stakeholder.GoogleCredentials'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"
