# Generated by Django 3.0.5 on 2021-04-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLUB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, upload_to='club/posters')),
                ('approved', models.BooleanField(default=False)),
                ('attendance', models.IntegerField(default=0)),
                ('club_name', models.CharField(max_length=100)),
                ('web_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CLUB_GENERAL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='club/logo')),
                ('club_email', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('coordinator1', models.CharField(max_length=100)),
                ('coordinator1_email', models.CharField(max_length=100)),
                ('coordinator2', models.CharField(blank=True, max_length=100)),
                ('coordinator2_email', models.CharField(blank=True, max_length=100)),
                ('coordinator3', models.CharField(blank=True, max_length=100)),
                ('coordinator3_email', models.CharField(blank=True, max_length=100)),
                ('fb_link', models.URLField(blank=True)),
                ('ig_link', models.URLField(blank=True)),
                ('website_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
    ]
